// ATOMIC COMPONENTS' TYPES DECLARATIONS

// ENUMS

// 1. ATOMS
// 1.1. Text

enum TextSize {
  HEADING_1 = "HEADING_1",
  HEADING_2 = "HEADING_2",
  HEADING_3 = "HEADING_3",
  HEADING_4 = "HEADING_4",
  TEXT_BASE = "TEXT_BASE",
  TEXT_SMALL = "TEXT_SMALL"
}